name: terraform
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - qa
      - staging
      - main
      - master
    paths-ignore:
      - ".images/**"
  pull_request:
    branches:
      - develop
      - qa
      - staging
      - main
      - master
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"
    paths-ignore:
      - ".images/**"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    env:
      BRANCH: ${{ github.base_ref || github.ref_name }}
    steps:
      - name: Get Stage
        run: |
          if [ $BRANCH == 'master' ] || [ $BRANCH == 'main' ]; then
            echo "STAGE=production" >> $GITHUB_ENV
          else
             echo "STAGE=$BRANCH" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure non prod AWS credentials
        if: env.STAGE != 'production'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.NON_PROD_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: ln-terraform-compute-terraform-ci
      - name: Configure prod AWS credentials
        if: env.STAGE == 'production'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: ln-terraform-compute-terraform-ci
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install python3-pip python3-setuptools jq
          sudo pip3 install terraenv awscli
          terraenv terragrunt install
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.6
      - name: Terraform Format
        id: fmt
        run: make fmt-check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: make init
      - name: Terraform Validate
        id: validate
        run: make init validate
      - name: Terraform Plan
        id: plan
        if: ${{ github.event_name == 'pull_request' }}
        run: make plan-ci
      - name: Comment PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
      - name: Terraform Apply
        if: ${{ github.event_name == 'push' }}
        run: make apply-ci